<h2>JOIN OUR MAILING LIST</h2>

<p> Receive email updates on stuff you'll probably want to know about, including products, launches,
    and events. Unsubscribe anytime. Oh, and for doing so, here's 5% off your first order</p>


<!--<p>-->
<!--    <a href="--><?php ///* echo $block->getLandingsUrl(); */ ?><!--"> Cái này mới này </a>-->
<!--</p>-->
<!--<p>-->
<!--    <a href="--><?php ///* echo $block->getRedirectUrl(); */ ?><!--"> Cái này mới nữa này </a>-->
<!--</p>-->