<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="minicart-wrapper">
    <div class="div-icon">
        <a class="link-text-icon"><p class="text-icon"><strong>Sign in</strong></p></a>
    </div>

    <div class="div-icon">
        <a class="action" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
           data-bind="scope: 'minicart_content'">
            <img src="<?php echo $this->getViewFileUrl('images/ngoisao.png'); ?>" />
        </a>
        <a class="link-text-icon"><p class="text-icon"><strong>Favorites</strong></p></a>
    </div>

    <div class="div-icon">
        <a class="action " href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
           data-bind="scope: 'minicart_content'">

            <img src="<?php echo $this->getViewFileUrl('images/kinhlup.png'); ?>" />

        </a>
        <a class="link-text-icon"><p class="text-icon"><strong>Search</strong></p></a>
    </div>

    <div class="div-icon">
        <a class="action" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
           data-bind="scope: 'minicart_content'">
            <img src="<?php echo $this->getViewFileUrl('images/tuixach.png'); ?>" />
        </a>
        <a class="link-text-icon"><p class="text-icon"><strong>Bag</strong></p></a>
    </div>



    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
            $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
        ) ?>"
        }
    }
    </script>
</div>


