<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$a = $_productCollection;
var_dump($_productCollection);
?>


<div class="owl-carousel owl-theme">
    <h1>Có rồi đây !!</h1>

</div>
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel ').owlCarousel({
                loop:false,
                nav:false,
                items:1,
                dots:true,
                autoplay:true,
                autoplayTimeout:3000
            })
        });
    });
</script>